### ISSUE TITLE
runtests.sh won't work with python 1.4+

### ISSUE THREAD

**Issue by TheSin-** [cdr-stats/cdr-stats#31]
```
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
```

This has been deprecated since 1.2 and removed in 1.4
